Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kbverlaan/GitProjects/autogen-podcast/autogen_podcast/main.py", line 61, in main
    with open(f'./output/script_{i-1}', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './output/script_4'
